### ISSUE TITLE
Feature: greater zoom out

### ISSUE THREAD

**Issue by quite** [sunng87/mapzei#2]
Would love to be able to zoom out more, to be able to easier identify where in the world and in what country I am  : ) Would that be possible?

**Comment by sunng87** [comment]
Thanks! In the settings screen, there is an option to configure default zoom level. You can always change it.

**Comment by sunng87** [comment]
Also, you can tap the city name in muzei to open the city map in Google Maps or any map app you have.

**Comment by quite** [comment]
Ah, I did not know you could tap the city name to show the map in any
app. That's a good solution for me. Thanks.

**Comment by sunng87** [comment]
Yes, that's Muzei feature. Hope you like it!
